# Generated by Django 4.1.7 on 2023-03-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[("RED", "Red"), ("GREEN", "Green"), ("BLUE", "Blue")],
                default="RED",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="excerpt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
