# Generated by Django 4.1.7 on 2023-03-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_color_product_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("RED", "Red"),
                    ("GREEN", "Green"),
                    ("BLUE", "Blue"),
                    ("BLACK", "Black"),
                ],
                default="RED",
                max_length=32,
            ),
        ),
    ]
